name: 'test code hexlet_pytest'
# on – определяет события, которые запускают воркфлоу
on:
  push:
  pull-request:
jobs:
  # операционная система для работы воркфлоу
  runs-on: ubuntu-latest
  steps: # список шагов, которые надо выполнить
    # экшен, выполняет какую-то задачу
    # checkout – клонирует репозиторий
    - uses: actions/checkout@v3
    # run – произвольная bash-команда
    - name: 'Install poetry'
      run: pip install poetry
    - name: 'Run test'
      run: poetry run pytest